### ISSUE TITLE
Windows releases error

### ISSUE THREAD

**Issue by LipeDuoli** [captainyarr/popcorntime-ce-desktop#11]
Hi,
The last 2 windows releases (both versions) are not working. When I open the program I get a error that is missing the locales. I try copy the locales from my old version but not work too. I think it's missing files from all folders (all are empty).

**Comment by captainyarr** [comment]
@LipeDuoli Let me check it out and see if I can update them. I will post up a new build tonight with corrected archive.

**Comment by captainyarr** [comment]
@LipeDuoli You where right about the missing files. I fixed the issue and posted a new release see 0.4.1-14 https://github.com/captainyarr/desktop/releases/tag/0.4.1-14
