### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by alfredo-ardito** [captainyarr/popcorntime-ce-desktop#136]
Subtitles are not working anymore. The icon on the bottom right does not display any language and country flag at all and when a play the movie no subtitle appears. This happens to all the movies listed.  

I've been using this package lot's of times without have any kind of issues. Its works like charm.

**Comment by captainyarr** [comment]
I noticed over the past few weeks there was a lot of server connection issues to opensubtitles.org I checked today and started seeing everything return to normal in terms of pulling the subtitles again.  You can try to flush the subtitles cache in the Settings and try to see everything gets pulled down again.

**Comment by alfredo-ardito** [comment]
Okay, I'll check it out this evening and let u know.
Thx

**Comment by alfredo-ardito** [comment]
Hello, I've checked in these days and, unfortunately, the subtitles are still not working. Probably opensubtitles.org is still having issues or they might have changed something.
I'll do other tests and let you know if anythings changed.

**Comment by alfredo-ardito** [comment]
Hello,  
I'm to inform you subtitles are back working as usual.
thx
