### ISSUE TITLE
TV Series not working

### ISSUE THREAD

**Issue by alfredo-ardito** [captainyarr/popcorntime-ce-desktop#142]
The TV Series isn't working anymore since a few weeks ago. I thought it was a temporary problem but it keeps on not working. I get the following message:

> The remote shows API failed to respond, please check http://status.popcorntime.ag and try again later

Any clue?

**Comment by captainyarr** [comment]
Trying to find a new TV API server.

**Comment by captainyarr** [comment]
I found a new tv api that works:

https://tv-v2.api-fetch.sh/

Copy the above into Settings for TV Show Endpoint

**Comment by alfredo-ardito** [comment]
cool, it works perfectly.
Thx
