### ISSUE TITLE
nwjs-sdk-v0.20.1-linux-x64.tar.gz

### ISSUE THREAD

**Issue by alfredo-ardito** [captainyarr/popcorntime-ce-desktop#18]
Hello
When executing  npm start
it tries to download the following file but it cannot find it.
Downloading: http://builds.butterproject.org/nw/v0.20.1/nwjs-sdk-v0.20.1-linux-x64.tar.gz
Any workaround?

**Comment by captainyarr** [comment]
Seems like the link is no longer available. We need to find an alternative link for the modified nwjs with FFMPEG included.

**Comment by captainyarr** [comment]
@alfredo-ardito 

Check develop branch for updated and working link.
