### ISSUE TITLE
It doesn't recognize VLC and Potplayer anymore

### ISSUE THREAD

**Issue by kartola** [captainyarr/popcorntime-ce-desktop#25]
Hi, the program doesn't recognize VLC and Potplayer anymore.

Please keep up the good work!

**Comment by captainyarr** [comment]
What OS are you using?  VLC is recognized just fine on my Linux laptop. Ensure your using the default location for install.

**Comment by kartola** [comment]
Windows 10
It use to recognize VLC and Potplayer but now (i don't know what changes...) it doesn't.
I tried to reset to default setting but nothing changes.

**Comment by captainyarr** [comment]
@kartola Can you post the full path here for VLC and PotPlayer from Win10?

**Comment by kartola** [comment]
C:\Program Files (x86)\VideoLAN\VLC
C:\Program Files\DAUM\PotPlayer

**Comment by captainyarr** [comment]
@kartola  

If you go into the debug console (F12) and type "win.debug(JSON.stringify(process.env));"

A whole bunch of stuff will appear but can you post the results here. I just check in Win7 and VLC was being detected as expected.

**Comment by kartola** [comment]
[DEBUG] {"3amDigitalStudios":"C:\\Program Files (x86)\\Common Files\\3am Digital Studios","ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\Damiano\\AppData\\Roaming","asl.log":"Destination=file","CHROME_CRASHPAD_PIPE_NAME":"\\\\.\\pipe\\crashpad_7632_TMHSBCJRBPLFFRIW","CHROME_PROBED_PROGRAM_FILES_PATH":"C:\\Program Files (x86)","CHROME_RESTART":"NW.js|Spiacenti, si è verificato un arresto anomalo di NW.js. Riavviarlo ora?|LEFT_TO_RIGHT","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"DAM","ComSpec":"C:\\WINDOWS\\system32\\cmd.exe","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","FPS_BROWSER_USER_PROFILE_STRING":"Default","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\Damiano","LOCALAPPDATA":"C:\\Users\\Damiano\\AppData\\Local","LOGONSERVER":"\\\\DAM","NUMBER_OF_PROCESSORS":"8","OneDrive":"C:\\Users\\Damiano\\OneDrive","OS":"Windows_NT","Path":"C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\Calibre2\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Common Files\\3am Digital Studios;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;%SystemRoot%\\system32;%SystemRoot%;%SystemRoot%\\System32\\Wbem;%SYSTEMROOT%\\System32\\WindowsPowerShell\\v1.0\\;%SYSTEMROOT%\\System32\\OpenSSH\\;C:\\Users\\Damiano\\AppData\\Local\\Microsoft\\WindowsApps;","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"Intel64 Family 6 Model 94 Stepping 3, GenuineIntel","PROCESSOR_LEVEL":"6","PROCESSOR_REVISION":"5e03","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","SESSIONNAME":"Console","SystemDrive":"C:","SystemRoot":"C:\\WINDOWS","TEMP":"C:\\Users\\Damiano\\AppData\\Local\\Temp","TMP":"C:\\Users\\Damiano\\AppData\\Local\\Temp","TZ":"America/New_York","USERDOMAIN":"DAM","USERDOMAIN_ROAMINGPROFILE":"DAM","USERNAME":"Damiano","USERPROFILE":"C:\\Users\\Damiano","windir":"C:\\WINDOWS"}

**Comment by kartola** [comment]
Maybe there is something wrong in my system. Now popcorntime doesn't load video anymore (it remains to connecting page...).
But the other popcorntime works...

**Comment by kartola** [comment]
Yes, something happened to the program... 
I re-extracted files in another folder and now everything works!
Everything but resolving torrent file or magnet link...
