### ISSUE TITLE
Executable files on latest release

### ISSUE THREAD

**Issue by LipeDuoli** [captainyarr/popcorntime-ce-desktop#41]
Hi,
The windows version, x86 and x64, of the latest release not have the executable files, only the nodejs and src

**Comment by captainyarr** [comment]
@LipeDuoli 

Let me look to re-build those and update them.

**Comment by captainyarr** [comment]
@LipeDuoli 

I just update the x86, and x64 release zips for the latest release.  Thanks for helping point this out.  Please download and check it out.

**Comment by LipeDuoli** [comment]
@captainyarr 
Everything is working now.. 
Thx for the quick fix
