### ISSUE TITLE
Downloads never starts

### ISSUE THREAD

**Issue by gabriel2185** [captainyarr/popcorntime-ce-desktop#42]
When I click on watch on the screen the message is displayed connecting a download never starts.

my operating system is win10 64bit and download and run popcorn-time-ce_win32_0.4.1-16.zip and popcorn-time-ce_win64_0.4.1-16.zip and in both cases the same thing happened.

It should be noted that the windows firewall asked me if I enabled this software and accept that request, in both versions. Distrusting that action creates a rule in the firewall to allow the entry and exit of transmissions from the popcorn executable.

This is my experience with the new version.

regards
Gabriel

**Comment by captainyarr** [comment]
Are you not able to get any downloads started? Try other selecting a different movie or TV shows with more seeds. It can wait for a long time trying to find others to connect with.

**Comment by gabriel2185** [comment]
I have to apologize since I did a test on another computer and this download problem does not happen. Feel free to close this topic.

Greetings from Argentina
Gabriel
