### ISSUE TITLE
video does not play inside Popcorn Time and in HTML5 mode

### ISSUE THREAD

**Issue by legluondunet** [captainyarr/popcorntime-ce-desktop#46]
Hello,
I just downloaded and compiled last git and I have some issues:
- playing video to HTML5 does not work: I obtain only a YTS logo on Firefox
- playing video inside Popcorn Time does not work and give me this error message:
This video could not be loaded, either the network or server failed or because the format is not supported.

In the terminal I have this log:
./Popcorn-Time-CE 
[14090:14109:1101/152118.957790:ERROR:nss_util.cc(731)] After loading Root Certs, loaded==false: NSS error code: -8018
[14137:14571:1101/152914.041207:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[14137:14137:1101/152914.041286:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS

I tested wirh VLC: video played with subtitles.

Thank you for your help.
my config:
Ubuntu 18.04 with Nvidia Graphic GPU

**Comment by captainyarr** [comment]
@legluondunet 

If your running it from the git develop branch make sure you update the ffmpeg library in the node.js cache version your using. I wrote a gulp task to update the cache version of the ffmpeg library with the pre-built version.

Run:
gulp ffmpegcache

That should update the ffmpeg library in the current version of nw.js your building against.

**Comment by legluondunet** [comment]
I follow your advice and it works now, thanks.
