### ISSUE TITLE
Automatic update breaks the next boot

### ISSUE THREAD

**Issue by gabriel2185** [captainyarr/popcorntime-ce-desktop#49]
in the win64_0.4.1-16 version there is a sign warning that an update was made and it requires a reboot, when I click on restart the application closes and does not restart. To solve this, it is necessary to download the application and deactivate automatic updates.
The version number that shows the warning does not correspond with the current one and I suspect that it may be updating from another server, is this possible?

regards

Gabriel Ordoñez

**Comment by captainyarr** [comment]
@gabriel2185 

I will look into this. Currently the automatic update functionality it not working or active in my builds.  It could be pulling from another server but I will change the default settings to de-activate the automatic updates.

**Comment by legluondunet** [comment]
same bug for me, after autoupdate I can no more launch Popcorn
