### ISSUE TITLE
Cannot load config file from /etc/fonts/fonts.conf

### ISSUE THREAD

**Issue by alfredo-ardito** [captainyarr/popcorntime-ce-desktop#90]
The program (Version 0.4.1-16 Beta) always worked perfectly without issues since last Monday when I updated my Arch Linux. After then the program doesn't run anymore and, instead, I'm getting the following errors:

> Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
> Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
> Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
> [7167:7167:0928/091118.319637:ERROR:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
> [7141:7176:0928/091118.332581:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 2
> [7141:7141:0928/091118.391355:FATAL:platform_font_linux.cc(83)] Check failed: InitDefaultFont(). Could not find the default font
> #0 0x7f3fb0e1166c <unknown>
> 
> Aborted (core dumped)
> 
The file /etc/fonts/fonts.conf exists and is good.
Any clues on how to get the program running again?

**Comment by captainyarr** [comment]
@alfredo-ardito 

Seems specific to your Arch setup with fonts.

Try running fontconfig to see if you can fix your system fonts
https://www.archlinux.org/packages/extra/x86_64/fontconfig/

**Comment by alfredo-ardito** [comment]
Thank u for replying. I've run fontconfig and everything seems to be okay. 
I'll try to do some more checking and see what's wrong.

In the mean while I also tried to run the program from the develop branch. Well the program runs well without throwing those errors about the missing fonts as mentioned above, BUT movies are not shown and instead I get the following error:

> The video could not be loaded, either because the server or network failed or because the format is not supported

Besides the video playback issue, I cannot use an external player like VLC because there's no option to use the VLC or other players.

**Comment by captainyarr** [comment]
@alfredo-ardito 

If your using the develop branch to fix the video error we have to update the ffmpeg library in the nw.js cache.

Update the nw.js cache:
`npx gulp ffmpegcache`

Update the build nw.js ffmpeg library:
`npx gulp ffmpegbuild`

This will update the right library to fix the video error.

VLC should be automatically detected if its installed in the default location.

```
    // linux
    addPath('/usr/bin');
    addPath('/usr/local/bin');
```

If Arch is using a different directory let me know.

**Comment by captainyarr** [comment]
@alfredo-ardito 

ok, you bring up a good point I am actually seeing an error in develop branch relating to external players.

**Comment by captainyarr** [comment]
@alfredo-ardito 

One of the package updates broke the external player detection. I just fixed it in the develop branch. When you get a chance pull the latest code and try it again on your side. This should be working now.

**Comment by alfredo-ardito** [comment]
@captainyarr 
Perfect. I built the develop branch using the above hints to fix the video error updating the ffmpeg library in the nw.js cache. Videos are now playing perfectly. 
All the external players are active and working.
Since the develop branch is perfectly working I'll stick to it and forget about the 0.4.1-16 version which seems to be faulty, at least, on my Arch system.

**Comment by captainyarr** [comment]
@alfredo-ardito 

Nice, thanks for letting me know that it fixed your issue.  I am working towards putting together a new release, but just trying to get clean it up a bit more.
