### ISSUE TITLE
Download Only button dosen't work

### ISSUE THREAD

**Issue by AndrejaN** [captainyarr/popcorntime-ce-desktop#96]
Hi,

when i hit the Download Only button, the movie is not saved on my local hard drive. Can you fix it?

One more thing. When i search through the folder where i'm downloading the movies, first there are random number name of the folders and then the folder with the name of the movie. When you have 40 movie it is not easy to find the movie within the folder with random number folders. 
Is it possible that in the download folder just download the movie title folder, not the random number folders and then the movie name?

Thanks, Andreja

**Comment by AndrejaN** [comment]
I have tested today, the code. It has to do something with the nw.js packages. because i have copied the code from your latest version into the old working version where the download is saving the files and it works.

**Comment by captainyarr** [comment]
@AndrejaN 

What version are you using or testing with?  The latest develop branch has it working in Linux from my testing.

**Comment by AndrejaN** [comment]
OK. i was working with older version from March 2019. Works now. Thanks
